name: Deploy frontend
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build dev image
        run: docker build -t cuevasgpablo/frontend_tests -f dockerfile.dev .

      - name: Run tests
        run: docker run -e -CI=true cuevasgpablo/frontend_tests npm run test:coverage

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build production image
        run: docker build -t cuevasgpablo/frontend -f dockerfile .

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-us-east-2-572263478950
          deployment_package: deploy.zip
          version_label: ${{ github.sha }}