name: Deploy frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build dev image
        run: docker build -t cuevasgpablo/frontend_tests -f dockerfile.dev .

      - name: Run tests
        run: docker run -e -CI=true cuevasgpablo/frontend_tests npm run test:coverage